language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - PHPUNIT_VERSION=dev-master
  - PHPUNIT_VERSION=~6.0.0

php:
  - 7.1
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - env: PHPUNIT_VERSION=dev-master

install:
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}
  - composer require squizlabs/php_codesniffer
  - composer require phpmd/phpmd

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode

